# Generated by Django 3.2.4 on 2021-06-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60, verbose_name='titulo')),
                ('subtitulo', models.CharField(max_length=120, verbose_name='subtitulo')),
                ('texto', models.TextField(max_length=1000, verbose_name='texto')),
            ],
        ),
    ]
